# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ColorCVT_UI.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(720, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(720, 720))
        mainWindow.setMaximumSize(QtCore.QSize(720, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.c3_h_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c3_h_label.sizePolicy().hasHeightForWidth())
        self.c3_h_label.setSizePolicy(sizePolicy)
        self.c3_h_label.setObjectName("c3_h_label")
        self.gridLayout.addWidget(self.c3_h_label, 7, 0, 1, 1)
        self.c3_h_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.c3_h_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.c3_h_horizontalSlider.setObjectName("c3_h_horizontalSlider")
        self.gridLayout.addWidget(self.c3_h_horizontalSlider, 7, 1, 1, 3)
        self.img_select_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.img_select_pushButton.setObjectName("img_select_pushButton")
        self.gridLayout.addWidget(self.img_select_pushButton, 0, 0, 1, 1)
        self.c2_l_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.c2_l_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.c2_l_horizontalSlider.setObjectName("c2_l_horizontalSlider")
        self.gridLayout.addWidget(self.c2_l_horizontalSlider, 4, 1, 1, 3)
        self.c2_h_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c2_h_label.sizePolicy().hasHeightForWidth())
        self.c2_h_label.setSizePolicy(sizePolicy)
        self.c2_h_label.setObjectName("c2_h_label")
        self.gridLayout.addWidget(self.c2_h_label, 5, 0, 1, 1)
        self.c2_h_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.c2_h_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.c2_h_horizontalSlider.setObjectName("c2_h_horizontalSlider")
        self.gridLayout.addWidget(self.c2_h_horizontalSlider, 5, 1, 1, 3)
        self.c3_l_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.c3_l_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.c3_l_horizontalSlider.setObjectName("c3_l_horizontalSlider")
        self.gridLayout.addWidget(self.c3_l_horizontalSlider, 6, 1, 1, 3)
        self.c3_l_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c3_l_label.sizePolicy().hasHeightForWidth())
        self.c3_l_label.setSizePolicy(sizePolicy)
        self.c3_l_label.setObjectName("c3_l_label")
        self.gridLayout.addWidget(self.c3_l_label, 6, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 4, 6, 1)
        self.c1_l_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c1_l_label.sizePolicy().hasHeightForWidth())
        self.c1_l_label.setSizePolicy(sizePolicy)
        self.c1_l_label.setObjectName("c1_l_label")
        self.gridLayout.addWidget(self.c1_l_label, 2, 0, 1, 1)
        self.c1_l_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c1_l_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.c1_l_horizontalSlider.setSizePolicy(sizePolicy)
        self.c1_l_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.c1_l_horizontalSlider.setObjectName("c1_l_horizontalSlider")
        self.gridLayout.addWidget(self.c1_l_horizontalSlider, 2, 1, 1, 3)
        self.img_label = QtWidgets.QLabel(self.centralwidget)
        self.img_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_label.sizePolicy().hasHeightForWidth())
        self.img_label.setSizePolicy(sizePolicy)
        self.img_label.setText("")
        self.img_label.setObjectName("img_label")
        self.gridLayout.addWidget(self.img_label, 1, 0, 1, 5)
        self.c1_h_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c1_h_label.sizePolicy().hasHeightForWidth())
        self.c1_h_label.setSizePolicy(sizePolicy)
        self.c1_h_label.setObjectName("c1_h_label")
        self.gridLayout.addWidget(self.c1_h_label, 3, 0, 1, 1)
        self.c1_h_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.c1_h_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.c1_h_horizontalSlider.setObjectName("c1_h_horizontalSlider")
        self.gridLayout.addWidget(self.c1_h_horizontalSlider, 3, 1, 1, 3)
        self.c2_l_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c2_l_label.sizePolicy().hasHeightForWidth())
        self.c2_l_label.setSizePolicy(sizePolicy)
        self.c2_l_label.setObjectName("c2_l_label")
        self.gridLayout.addWidget(self.c2_l_label, 4, 0, 1, 1)
        self.hsv_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hsv_radioButton.sizePolicy().hasHeightForWidth())
        self.hsv_radioButton.setSizePolicy(sizePolicy)
        self.hsv_radioButton.setChecked(False)
        self.hsv_radioButton.setObjectName("hsv_radioButton")
        self.gridLayout.addWidget(self.hsv_radioButton, 0, 1, 1, 1)
        self.hls_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hls_radioButton.sizePolicy().hasHeightForWidth())
        self.hls_radioButton.setSizePolicy(sizePolicy)
        self.hls_radioButton.setCheckable(True)
        self.hls_radioButton.setChecked(False)
        self.hls_radioButton.setObjectName("hls_radioButton")
        self.gridLayout.addWidget(self.hls_radioButton, 0, 2, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "ColorCVT"))
        self.c3_h_label.setText(_translate("mainWindow", "c3_h"))
        self.img_select_pushButton.setText(_translate("mainWindow", "选择图片"))
        self.c2_h_label.setText(_translate("mainWindow", "c2_h"))
        self.c3_l_label.setText(_translate("mainWindow", "c3_l"))
        self.c1_l_label.setText(_translate("mainWindow", "c1_l"))
        self.c1_h_label.setText(_translate("mainWindow", "c1_h"))
        self.c2_l_label.setText(_translate("mainWindow", "c2_l"))
        self.hsv_radioButton.setText(_translate("mainWindow", "HSV"))
        self.hls_radioButton.setText(_translate("mainWindow", "HLS"))

